### PR TITLE
Update to support parity API 0.7.0

### PR DESCRIPTION
**Pull request by Neopallium**

### CODE REVIEW

**Comment by jvirtanen** [comment]
@Neopallium As discussed on https://github.com/jvirtanen/parity-ticker/pull/1, I'm happy to take a look after the changes related to the fractional digits. Please ping me so that I don't miss the notification. Thank you for all your efforts so far! 🙌

**Comment by Neopallium** [comment]
@jvirtanen Added support for fractional digits of both price and size.

Also added support for simulating multiple instruments.

**Comment by jvirtanen** [comment]
I'm a bit conflicted about adding support for multiple instruments as that adds some complexity that could be avoided by simply running multiple instances of the application. The latter is the approach I took in [Genesis Replicator](https://github.com/jvirtanen/genesis/tree/master/applications/replicator), which is a fairly similar application to this.

Also as in Genesis Replicator, perhaps we could simply add `priceFactor` and `sizeFactor` beside `instrument` in the configuration file? (I just realized that the `Instruments` approach does not work very well here as e.g. [`Instrument.fromConfig`](https://github.com/paritytrading/parity/blob/4d10461168a98dbdf4443bc1e6bf3ac84c92770c/libraries/util/src/main/java/com/paritytrading/parity/util/Instrument.java#L120) is not part of the public interface.)

**Comment by Neopallium** [comment]
I wanted to keep the instrument settings the same as the other projects and to use `Instruments.fromConfig` like the other projects.

I don't think it makes it that much more complected.

Each instrument will get it's own thread.  Which is about the same as running multiple instances (one for each instrument).  I could have made the `Events` class support multiple `MarketData` instances, then only one thread would have been needed.  But it was easier to use multiple threads for now.

I think the `Events` class could possibly have been implemented using an event loop library like Netty.

**Comment by jvirtanen** [comment]
@Neopallium I will have a look at this on the weekend. 👍  My apologies for the delay!

**Comment by jvirtanen** [comment]
I still feel that this pull request is trying to introduce two quite distinct changes:
- Updating to Parity 0.7.0
- Adding support for multiple simulator instances

It would be nice if you could look into the Parity 0.7.0 support keeping the current architecture of one simulator instance per process. This should be quite easily doable on top of the initial commit, 
ac07d8b, with the introduction of `priceFactor` and `sizeFactor` configuration options. This would also be in line with [Genesis Replicator](https://github.com/jvirtanen/genesis/tree/master/applications/replicator), which in many ways a sibling of this application. 🙂 

What do you think?

**Comment by Neopallium** [comment]
I removed the multiple simulator commit and reworked the `priceFactor` and `sizeFactor` commits.

Since `Instrument` construction is private, I just did the same logic for calculating `priceFactor` and `sizeFactor`.

**Pull request closed without merging**
